stages:
  - fetch-scripts
  - install-gams
  - build
  - test
  - pack
  - deploy
  - analyze

include:
  - project: 'devel/ciscripts'
    file: .install-jobs.yml
  - project: 'devel/ciscripts'
    file: .shared-vars.yml
  - 'ci/.gitlab-ci-06-gams.yml'
  - 'ci/.gitlab-ci-09-build.yml'
  - 'ci/.gitlab-ci-12-test.yml'
  - 'ci/.gitlab-ci-15-pack.yml'
  - 'ci/.gitlab-ci-20-analyze.yml'
  - 'ci/.gitlab-ci-24-deploy.yml'

variables:
  extends: .shared-variables
  GAMS_CONTAINER_REGISTRY:
      value: registry.gams.com/devel
      description: "URL to the GAMS container registry"
  PF_WEI_DEBUG:
      value: 0
      description: "A value != 0 builds the Windows debug version only"
  PF_CUSTOM_BRANCH:
      value: $CUSTOM_BRANCH
      description: "Name of custom branch, 0 if published distribution with version as specified should be taken or X.Y.Z"
