stages:
  - fetch-prerequisites
  - install-gams
  - build
  - test
  - pack
  - deploy
  - analyze

variables:
  GAMS_CONTAINER_REGISTRY:
      value: registry.gams.com/devel
      description: "URL to the GAMS container registry"
  PF_CUSTOM_BRANCH:
      value: $CUSTOM_BRANCH
      description: "Name of custom branch or 0 if published distribution with version as specified should be taken"
  PF_BUILDS_WWW_PATH:
      value: $BUILDS_WWW_PATH
      description: "URL path prefix for builds server"
  PF_BUILDS_SSH_PORT:
      value: $BUILDS_SSH_PORT
      description: "Port used for SSH connection to builds server"
  PF_BUILDS_SSH_SERVER:
      value: $BUILDS_SSH_SERVER
      description: "URL of the build server"
  PF_BUILDS_SSH_USER:
      value: $BUILDS_SSH_USER
      description: "Username used for SSH connection to builds server"
  PF_GAMS_LICENSE:
      value: $GAMS_LICENSE
      description: "GAMS license string used for testing"

include: ['ci/.gitlab-ci-06-gams.yml'
         ,'ci/.gitlab-ci-09-build.yml'
         ,'ci/.gitlab-ci-12-test.yml'
         ,'ci/.gitlab-ci-15-pack.yml'
         ,'ci/.gitlab-ci-20-analyze.yml'
         ,'ci/.gitlab-ci-24-deploy.yml'
         ]
