test-dac:
  stage: test
  tags: [macos-arm64]
  allow_failure: true
  dependencies: [install-gams-dac,build-dac]
  variables:
    qtpath: /Users/gitlab/Qt/6.4.3/macos/bin
  script:
    - GAMS_PATH=$(pwd)/gamsdist
    - PATH="${qtpath}:${GAMS_PATH}:${PATH}"
    - echo $PF_GAMS_LICENSE > $GAMS_PATH/gamslice.txt
    - cd build && mkdir reports
    - REPORTS_DIR=$(pwd)/reports
    - |+
      set +e
      cd tests/bin
      for f in *
      do
        ./$f -xunitxml -o $REPORTS_DIR/$f.xml
      done
  artifacts:
    name: unittest-results-dac
    paths: 
      - build/reports/*
      - build/src/bin/*
    reports:
      junit: build/reports/*

test-deg:
  stage: test
  tags: [macos]
  allow_failure: true
  dependencies: [install-gams-deg,build-deg]
  variables:
    qtpath: /Users/gitlab/Qt/6.4.3/macos/bin
  script:
    - GAMS_PATH=$(pwd)/gamsdist
    - PATH="${qtpath}:${GAMS_PATH}:${PATH}"
    - echo $PF_GAMS_LICENSE > $GAMS_PATH/gamslice.txt
    - cd build && mkdir reports
    - REPORTS_DIR=$(pwd)/reports
    - |+
      set +e
      cd tests/bin
      for f in *
      do
        ./$f -xunitxml -o $REPORTS_DIR/$f.xml
      done
  artifacts:
    name: unittest-results-deg
    paths: 
      - build/reports/*
      - build/src/bin/*
    reports:
      junit: build/reports/*

test-leg:
  stage: test
  tags: [linux]
  allow_failure: true
  image:
    name: $GAMS_CONTAINER_REGISTRY/qt-machines/leg/builder-qt6:latest
    entrypoint: [""]   # prevent startup.sh
  dependencies: [install-gams-leg,build-leg]
  variables:
    qtpath: /opt/Qt/6.4.2/bin
  script:
    - GAMS_PATH=$(pwd)/gamsdist
    - PATH="${qtpath}:${GAMS_PATH}:${PATH}"
    - cd build && mkdir reports
    - REPORTS_DIR=$(pwd)/reports
    - |+
      set +e
      cd tests/bin
      for f in *
      do
        xvfb-run ./$f -xunitxml -o $REPORTS_DIR/$f.xml
      done
  artifacts:
    name: unittest-results-deg
    paths: 
      - build/reports/*
      - build/src/bin/*
    reports:
      junit: build/reports/*

test-wei:
  stage: test
  tags: [windows]
  allow_failure: true
  image:
    name: $GAMS_CONTAINER_REGISTRY/qt-machines/wei/builder-qt6:latest
  dependencies: [install-gams-wei,build-wei]
  variables:
    qtpath: C:\Qt\6.4.2\msvc2019_64\bin
  script:
    - $GAMS_PATH = ($(pwd), '\gamsdist') -join ""
    - Out-File -FilePath $GAMS_PATH\gamslice.txt -InputObject $PF_GAMS_LICENSE -Encoding ASCII
    - $env:Path = "$qtpath;$GAMS_PATH;$GAMS_PATH\gbin;" + $env:Path
    - $env:GAMSDIR = "$GAMS_PATH;$GAMS_PATH\gbin"
    - findthisgams -q
    - cd build
    - mkdir reports
    - $data = 
      ('cd tests/bin',
      'set STATE=0',
      'for %%f in (*) do (',
      '%%f -xunitxml -o ..\\..\\reports\\%%f.xml',
      'if not "%errorlevel%"=="0" set STATE=1',
      'echo errorlevel %errorlevel%',
      ')',
      'cd ../../reports',
      'for %%f in (*) do (',
      '>nul find /c "testcase result=""fail""" %%f && exit 5', 
      ')',
      'exit 0'
      )
    - $data | out-file -encoding ascii test.bat
    - ./test.bat
  artifacts:
    name: unittest-results-wei
    paths:
      - build/reports/*
      - build/src/bin/*
    reports:
      junit: build/reports/*
