pack-deg:
  stage: pack
  tags: [macos]
  variables:
    qtpath: /Users/gitlab/Qt/6.4.3/macos/bin
  needs: [build-deg]
  script:
    - WORKSPACE=$(pwd)
    - PATH="${qtpath}:${PATH}"
    - cd build/src/bin
    - macdeployqt "modelinspector.app" -always-overwrite
    - codesign --sign ${GAMS_CODESIGN_IDENTITY} --options runtime --force --deep --timestamp --entitlements $WORKSPACE/platform/macos/modelinspector.entitlements.plist "modelinspector.app"
    - hdiutil create -volname "modelinspector" -srcfolder "modelinspector.app" -ov -fs HFS+ -format UDZO "modelinspector.dmg"  
    - codesign --verify --verbose modelinspector.app
    - mv "modelinspector.dmg" "$WORKSPACE/model-inspector-deg-x86_64.dmg"
  artifacts:
    name: "model-inspector-deg-x86_64"
    paths: ['model-inspector-deg-x86_64.dmg']
    expose_as: 'model-inspector-deg-x86_64'
    expire_in: 1 days

pack-leg:
  stage: pack
  tags: [linux]
  image:
    name: $GAMS_CONTAINER_REGISTRY/qt-machines/leg/builder-qt6:latest
    entrypoint: [""]   # prevent startup.sh
  needs: [build-leg]
  variables:
    qtpath: /opt/Qt/6.4.2/bin
  script:
    # setup environment
    - PATH="${qtpath}:${PATH}"
    # create folder structure
    - mkdir -p appdir/usr/bin
    - mkdir -p appdir/usr/share/pixmaps
    - mkdir -p appdir/usr/resources
    # collect files
    - cp build/src/bin/modelinspector appdir/usr/bin/
    - cp -r icons/* appdir/usr/share/pixmaps
    - cp platform/linux/modelinspector.desktop appdir/usr/share/modelinspector.desktop
    # build the AppImage
    - /opt/linuxdeploy/linuxdeploy-x86_64.AppImage --appdir=appdir --plugin=qt --output=appimage --desktop-file=appdir/usr/share/modelinspector.desktop 
    - mv Model_Inspector-x86_64.AppImage model-inspector-leg-x86_64.AppImage
  artifacts:
    name: "model-inspector-leg-x86_64"
    paths: ['model-inspector-leg-x86_64.AppImage']
    expose_as: 'model-inspector-leg-x86_64'
    expire_in: 1 days

pack-wei:
  stage: pack
  tags: [windows]
  image:
    name: $GAMS_CONTAINER_REGISTRY/qt-machines/wei/builder-qt6:latest
  needs: [build-wei]
  variables:
    vcinsdir: C:\Program Files\Microsoft Visual Studio\2022\Community\VC
    cmd_vcvars: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat
  script:
    - $env:VCINSTALLDIR = "$vcinsdir"
    - $env:Path = "C:\Qt\6.4.2\msvc2019_64\bin;" + $env:Path
    - '& $cmd_vcvars'
    - mkdir model-inspector
    - cp "/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Redist/MSVC/14.29.30133/x64/Microsoft.VC142.CRT/*" "model-inspector"
    - cp "/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Redist/MSVC/14.29.30133/vc_redist.x64.exe" "model-inspector"
    - cp build/src/bin/* model-inspector
    - cd model-inspector
    - 'windeployqt --release --compiler-runtime --force modelinspector.exe'
    - echo $GAMS_COMODO_CERT | out-file -encoding ascii comodo_code.dat
    - $data = (
      'import base64;',
      'import sys;',
      'base64.decode(open(sys.argv[1], ''rb''), open(sys.argv[2], ''wb''))'
      )
    - $data | out-file -encoding ascii test.py
    - python test.py comodo_code.dat comodo_cert.p12
    - signtool sign /v /f comodo_cert.p12 /p $GAMS_COMODO_CERT_PASSWORD /t http://timestamp.comodoca.com modelinspector.exe
    - rm comodo_code.dat
    - rm comodo_cert.p12
    - cd ..
    - Compress-Archive -Path model-inspector -DestinationPath model-inspector-wei-x86_64.zip
  artifacts:
    name: "model-inspector-wei-x86_64"
    paths: ['model-inspector-wei-x86_64.zip']
    expose_as: 'model-inspector-wei-x86_64'
    expire_in: 1 days
